## INFO: No CDC present in axi_vdma_0
## INFO: When C_PRMRY_IS_ACLK_ASYNC = 0, AXI-VDMA MANDATORY REQUIREMENT IS THAT ALL AXI-VDMA CLOCK PORTS MUST BE CONNECTED TO THE SAME CLOCK SOURCE HAVING SAME FREQUENCY i.e. THERE IS ONLY ONE CLOCK-DOMAIN IN THE ENTIRE axi_vdma_0 DESIGN
## INFO: PLEASE ENSURE THIS REQUIREMENT IS MET.
#
#


